name:                poly
version:             0.1.0.0
github:              "githubuser/poly"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/poly#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- text-show
- parser-combinators
- haskeline
- prettyprinter
- mtl
- transformers
- containers
- either
- dlist

# quickcheck stuff
- QuickCheck
- generic-random
- quickcheck-instances

default-extensions:
- OverloadedStrings
- OverloadedLists
- LambdaCase
- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ApplicativeDo
- TupleSections
- InstanceSigs
- TypeApplications
- DeriveGeneric

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  poly-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poly

tests:
  poly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poly
    - hspec
    - QuickCheck
